export const toolGroups = [
  {
    title: '程序员核心开发工具',
    items: [
      {
        label: 'JSON 格式化',
        path: '/json-formatter',
        icon: 'Document',
        title: 'JSON 格式化/校验工具',
        description: '在线 JSON 格式化、校验、美化与压缩工具，纯前端本地处理，JSON 内容不会上传服务器。',
        keywords: 'JSON格式化,在线JSON校验,JSON压缩,JSON美化,JSON工具',
      },
      {
        label: '时间戳转换',
        path: '/timestamp-converter',
        icon: 'Clock',
        title: '时间戳转换工具',
        description: '时间戳与日期时间双向转换，支持毫秒和秒级单位，浏览器端本地处理更安全。',
        keywords: '时间戳转换,在线时间戳工具,日期转时间戳,毫秒时间戳,秒时间戳',
      },
      {
        label: 'URL 编解码',
        path: '/url-codec',
        icon: 'Link',
        title: 'URL 编解码工具',
        description: '在线 URL 编码与解码工具，支持特殊字符处理，纯前端本地转换，结果即时可复制。',
        keywords: 'URL编码,URL解码,在线URL工具,encodeURIComponent,decodeURIComponent',
      },
      {
        label: '密码生成器',
        path: '/password-generator',
        icon: 'Key',
        title: '随机密码生成器',
        description: '一键生成高强度随机密码，支持长度与字符类型配置，密码仅在浏览器本地生成。',
        keywords: '密码生成器,随机密码,在线密码工具,强密码生成,安全密码',
      },
      {
        label: 'Base64 编解码',
        path: '/base64-codec',
        icon: 'DocumentCopy',
        title: 'Base64 编解码工具',
        description: '支持文本与图片 Base64 编码、解码和下载，浏览器端本地转换，适合接口调试与前端开发。',
        keywords: 'Base64编码,Base64解码,在线Base64工具,图片转Base64,文本Base64',
      },
      {
        label: 'UUID 生成器',
        path: '/uuid-generator',
        icon: 'CollectionTag',
        title: 'UUID 在线生成器',
        description: '一键批量生成 UUID/GUID，支持批量复制与下载，适合主键、唯一标识与测试数据生成。',
        keywords: 'UUID生成器,GUID生成,在线UUID,随机唯一标识,UUID批量生成',
      },
      {
        label: '颜色值转换',
        path: '/color-converter',
        icon: 'MagicStick',
        title: '颜色值转换工具',
        description: '支持 HEX、RGB、RGBA、HSL 互转，适合前端开发、UI 联调与设计标注场景。',
        keywords: '颜色转换,HEX转RGB,RGB转HSL,在线颜色工具,RGBA转换',
      },
      {
        label: 'HTML 实体编解码',
        path: '/html-entity-codec',
        icon: 'Operation',
        title: 'HTML 实体编解码工具',
        description: '特殊字符与 HTML 实体一键互转，适合富文本处理、转义排查与前端安全场景。',
        keywords: 'HTML实体编码,HTML实体解码,在线转义工具,特殊字符转义,HTML Encode',
      },
    ],
  },
  {
    title: '通用文本处理工具',
    items: [
      {
        label: '文本统计',
        path: '/text-stats',
        icon: 'DataAnalysis',
        title: '文本字数统计工具',
        description: '快速统计字数、字符数、行数、段落数和词数，适合文案、报告、论文与开发文本处理。',
        keywords: '字数统计,字符统计,在线文本统计,行数统计,词数统计',
      },
      {
        label: '大小写转换',
        path: '/text-case-converter',
        icon: 'EditPen',
        title: '文本大小写转换工具',
        description: '支持大写、小写、标题式、驼峰、蛇形和短横线命名转换，适合开发与文案整理。',
        keywords: '大小写转换,在线英文转换,驼峰转换,snake_case,kebab-case',
      },
      {
        label: '文本清洗',
        path: '/text-cleaner',
        icon: 'Files',
        title: '文本清洗工具',
        description: '去重、去空格、去空行、整理换行与分隔符，适合数据清洗、名单整理与批量文本处理。',
        keywords: '文本去重,文本清洗,在线去空格,换行替换,文本整理',
      },
    ],
  },
  {
    title: '图片/文件处理工具',
    items: [
      {
        label: '图片压缩',
        path: '/image-compressor',
        icon: 'PictureFilled',
        title: '图片压缩工具',
        description: '纯前端在线图片压缩工具，支持 JPG/PNG，压缩前后对比清晰，图片不上传服务器。',
        keywords: '图片压缩,在线压缩图片,JPG压缩,PNG压缩,前端图片压缩',
      },
      {
        label: '图片格式转换',
        path: '/image-format-converter',
        icon: 'Picture',
        title: '图片格式转换工具',
        description: '支持 JPG、PNG、WebP 互转与质量调整，纯前端本地处理，更适合配图和素材整理。',
        keywords: '图片格式转换,JPG转PNG,PNG转WebP,在线图片转换,WebP转换',
      },
    ],
  },
  {
    title: '职场效率工具',
    items: [
      {
        label: '人民币大写',
        path: '/rmb-uppercase',
        icon: 'Coin',
        title: '人民币大写金额转换工具',
        description: '数字金额一键转人民币大写，适合报销、合同、发票和财务单据填写。',
        keywords: '人民币大写,在线金额转换,大写金额,发票金额转换,财务工具',
      },
      {
        label: '日期差/工作日',
        path: '/date-diff-calculator',
        icon: 'Calendar',
        title: '日期差与工作日计算器',
        description: '快速计算两个日期之间的自然日、含首尾天数、工作日和周数，适合排期与请假场景。',
        keywords: '日期差计算器,工作日计算,在线日期计算,天数计算,排期工具',
      },
      {
        label: '单位换算',
        path: '/unit-converter',
        icon: 'Postcard',
        title: '常用单位换算工具',
        description: '覆盖长度、重量、温度、面积、速度、时间和存储单位换算，打开即用。',
        keywords: '单位换算,在线换算器,长度换算,温度换算,存储换算',
      },
      {
        label: '随机抽签',
        path: '/random-picker',
        icon: 'Management',
        title: '随机数与随机抽签工具',
        description: '支持随机数生成、随机抽签和名单分组，适合会议抽签、活动摇号和日常分配。',
        keywords: '随机数生成,随机抽签,在线抽签,名单随机,摇号工具',
      },
      {
        label: '二维码生成',
        path: '/qrcode-generator',
        icon: 'Tickets',
        title: '二维码生成器',
        description: '输入链接、文字或联系方式即可生成二维码，支持尺寸与纠错级别调节。',
        keywords: '二维码生成器,在线生成二维码,链接转二维码,文字二维码,QR Code',
      },
    ],
  },
  {
    title: '编码/加密解密工具',
    items: [
      {
        label: '编码转换器',
        path: '/encoding-converter',
        icon: 'DocumentCopy',
        title: '文本编码转换器',
        description: '支持 UTF-8、GBK、GB2312、Latin-1、UTF-16、Big5 等文本编码互转，并可自动检测源编码。',
        keywords: '编码转换,UTF-8转GBK,GB2312转UTF8,Latin1转换,Big5转换,文本编码工具',
      },
      {
        label: '哈希计算',
        path: '/hash-calculator',
        icon: 'Key',
        title: '哈希计算工具',
        description: '支持 MD5、SHA1、SHA256、SHA512 文本与文件哈希计算，适合校验、签名与开发联调。',
        keywords: 'MD5计算,SHA256计算,在线哈希工具,文件哈希,文本哈希',
      },
    ],
  },
  {
    title: '轻量辅助工具',
    items: [
      {
        label: '在线便签',
        path: '/local-notes',
        icon: 'Memo',
        title: '在线便签记事本',
        description: '本地自动保存的浏览器便签，不依赖账号和后端，适合随手记录临时事项和片段内容。',
        keywords: '在线便签,浏览器记事本,本地记事本,临时笔记,localStorage便签',
      },
      {
        label: '在线计时器',
        path: '/timer-tool',
        icon: 'Timer',
        title: '在线倒计时与秒表工具',
        description: '支持浏览器端倒计时与秒表计时，适合会议、演讲、番茄钟和日常专注计时。',
        keywords: '在线倒计时,在线秒表,计时器,专注计时,番茄钟工具',
      },
    ],
  },
];

export const toolRoutes = toolGroups.flatMap((group) => group.items);
